# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KarbalaIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarbalaIOS

 pod 'BEMCheckBox'
  pod 'libPhoneNumber-iOS'
  pod 'SwiftMessages'
  pod 'IQKeyboardManagerSwift'
  pod 'UITextView+Placeholder'
  pod 'SKPhotoBrowser'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SDWebImage'
  pod 'YPImagePicker'
  pod 'Alamofire','~>4.9.1'
  pod 'NVActivityIndicatorView'
  pod "SkeletonView"
  pod 'CountryPickerView'
pod 'Firebase/Analytics'

end
